### PR TITLE
Refactor to match ORACLE Java Development Style Guide | DO NOT MERGE UNTIL TESTED

### LINKED ISSUE #33: Refactor to match conventions
The codebase needs to be refactored in the following ways:
- Use lowercase package names
- New folder structure to improve readability. I suggest the following:
```
java/
├─ frc/
│  ├─ robot/
│  │  ├─ subsystem/
│  │  │  ├─ arm/
│  │  │  │  ├─ commands/
│  │  │  │  │  ├─ Cmd_SubSys_Arm_JoyStickDefault.java
│  │  │  │  ├─ SubSys_Arm.java
│  │  │  │  ├─ SubSys_Arm_Constants.java
│  │  ├─ Constants.java
│  │  ├─ Main.java
│  │  ├─ Robot.java
│  │  ├─ RobotContainer.java

```

### PR DESCRIPTION
**Pull request by SeanErn**
DO NOT MERGE THIS UNTIL IT IS TESTED AND DECIDED ON.

THIS IS NOT A FINAL PRODUCT. USE THIS SPACE FOR FEEDBACK AND SUGESSTIONS

### CODE REVIEW

**Comment by chrisdeboer** [comment]
This looks good with the exception of the subsystems folder.  I liked having the GameName first and then subsystems, so it makes it more obvious where to put game specific code and library code.  Not everyone inherently knows what a library is.  I also like the ability to keep last years code and this years code separate but still in the same repository.  We could have subsystems with the same names in the old and new folders as we work on prototypes early in the season.  I would just add folders chargedup/subsystems and crescendo/subsystems and put DriverStation.java in the correct year since that is always game specific.

**Comment by SeanErn** [comment]
> This looks good with the exception of the subsystems folder. I liked having the GameName first and then subsystems, so it makes it more obvious where to put game specific code and library code. Not everyone inherently knows what a library is. I also like the ability to keep last years code and this years code separate but still in the same repository. We could have subsystems with the same names in the old and new folders as we work on prototypes early in the season. I would just add folders chargedup/subsystems and crescendo/subsystems and put DriverStation.java in the correct year since that is always game specific.

I'm having trouble understanding what exactly you mean by "having subsystems with the same names in the old and new folders." Do you mean having a folder named "new" and one named "old" with each respective iteration of the subsystems? It would be helpful if you could use GitHub's code review feature to write comments on where you want it changed or push an example to this PR? 

Also, the list is still a work in progress. Almost done.

**Comment by chrisdeboer** [comment]
Let me try to clarify.  I like this folder structure.

java
  frc
    robot
      library
      chargedup
        commands         
        arm
        hand 
        DriverStation.java
      crescendo
        commands         
        arm
        hand 
        DriverStation.java

**Comment by SeanErn** [comment]
On dev branch

**Pull request closed without merging**
